// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpP3VZScnSzdOYtun8DUD__KDAvZATpBg',
    appId: '1:1064950690516:web:20ef80bc2f0e8b15704141',
    messagingSenderId: '1064950690516',
    projectId: 'tamimgpt3chat',
    authDomain: 'tamimgpt3chat.firebaseapp.com',
    storageBucket: 'tamimgpt3chat.appspot.com',
    measurementId: 'G-DNMYGYMRJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPGw6yl3p3Q-Jn0o5fc8uuM3GAqcGCKKw',
    appId: '1:1064950690516:android:90157cd68b67f440704141',
    messagingSenderId: '1064950690516',
    projectId: 'tamimgpt3chat',
    storageBucket: 'tamimgpt3chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFlUNKnhUzOxr2Dvtvk4lpqZC8AW5gito',
    appId: '1:1064950690516:ios:d16b251b13108c8c704141',
    messagingSenderId: '1064950690516',
    projectId: 'tamimgpt3chat',
    storageBucket: 'tamimgpt3chat.appspot.com',
    iosClientId: '1064950690516-mijmiav5vg0o5gc7sfv3humpuansb56e.apps.googleusercontent.com',
    iosBundleId: 'com.example.tamimgpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFlUNKnhUzOxr2Dvtvk4lpqZC8AW5gito',
    appId: '1:1064950690516:ios:a99b0e2adfbc0259704141',
    messagingSenderId: '1064950690516',
    projectId: 'tamimgpt3chat',
    storageBucket: 'tamimgpt3chat.appspot.com',
    iosClientId: '1064950690516-tj0ki6umcbsh95qp4enm49c6lr0hi829.apps.googleusercontent.com',
    iosBundleId: 'com.example.tamimgpt.RunnerTests',
  );
}
